### ISSUE TITLE
Allow registering custom functions

### ISSUE THREAD

**Issue by joeyjurjens** [textwire/textwire#18]
First of all; What a great templating library!

Textwire comes with built in functions, and the docs state creating an issue if you any function suggestions.

But what about allowing users to register functions themselves, would that be something for textwire?

**Comment by SerhiiCho** [comment]
Thanks for the issue. The ability to define your functions is a great idea. I'll add it next

**Comment by SerhiiCho** [comment]
@joeyjurjens what do you think about this API?

```go
tpl, err = textwire.NewTemplate(&textwire.Config{
	TemplateDir: "templates",
	StrFuncs: map[string]textwire.StrFunc{
		"reverse": func(s string) string {
			runes := []rune(s)

			for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
				runes[i], runes[j] = runes[j], runes[i]
			}

			return string(runes)
		},
	},
})
```

**Comment by SerhiiCho** [comment]
The same way we'll be able to define a function for any type:

```go
tpl, err = textwire.NewTemplate(&textwire.Config{
	TemplateDir: "templates",
	StrFuncs:    map[string]textwire.StrFunc{},
	ArrFuncs:    map[string]textwire.ArrFunc{},
	IntFuncs:    map[string]textwire.IntFunc{},
	FloatFuncs:  map[string]textwire.FloatFunc{},
})
```

here are callback types:

```go
type StrFunc func(string) string
type ArrFunc func([]interface{}) []string
type IntFunc func(int) int
type FloatFunc func(float64) float64
```

**Comment by joeyjurjens** [comment]
Yes! that's indeed the kind of API I would expect. :)

**Comment by SerhiiCho** [comment]
I went a little bit different route, the API for defining a function will be something like this:

```go
RegisterIntFunc("double", func(num int, args ...interface{}) int {
    return num * 2
})
```

You can also pass arguments to custom functions:
```go
RegisterStrFunc("concat", func(s string, args ...interface{}) string {
    arg1Value := args[0].(string)
    arg2Value := args[1].(string)

    return s + arg1Value + arg2Value
})
```

The usage is usual:

```html
<span>{{ 'john'.concat(' ', 'doe') }}</span> <!-- will print: john doe -->
```

I'll finish tomorrow, gotta write more tests to make sure it works correctly and reflect it docs. The only downside is that it's going to be a major version update v2. For the usage you'll need to add `/v2` to the package like this: `github.com/textwire/textwire/v2`. Just a common practice in Go

**Comment by SerhiiCho** [comment]
I'll update docs, but for now:

## Update guide from `v1` to `v2`
1. Change all the imports from `github.com/textwire/textwire` to `github.com/textwire/textwire/v2`
2. Run `go mod tidy` to update the dependencies
3. Change the package name from `textwire.Config` to `config.Config` in your code if you use configuration and import `"github.com/textwire/textwire/v2/config"`. If you already have a package named `config`, you can alias the import like `twconfig "github.com/textwire/textwire/v2/config"`

**Comment by joeyjurjens** [comment]
Cool, thanks man! :)

**Comment by SerhiiCho** [comment]
Finally updated docs, add [upgrade guide](https://textwire.github.io/docs/v2/upgrade) and [custom functions](https://textwire.github.io/docs/v2/guides/custom-functions) information. If you encounter any issues, I'll quickly help.

Thank you, @joeyjurjens, for your feedback, in the next 2 days I'll add more built-in functions

**Comment by SerhiiCho** [comment]
> Cool, thanks man! :)

Please keep in mind that there are new functions added in new releases, to prevent interfering with built-in functions, prefix your custom functions with "_". Built-in functions have a higher priority, they will overwrite the behavior of custom ones
